// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/BatchJobBundle/Entity/BatchJob.php
// Table: `BatchJob`, REST: `/api/batch_jobs`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct BatchJob {
    pub id: i32,
    pub name: String,
    #[sqlx(rename = "baseEntity")]
    pub base_entity: String,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<BatchJob>>, (StatusCode, String)>
{
    sqlx::query_as::<_, BatchJob>("SELECT * FROM `BatchJob` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in BatchJob::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
