// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/BatchJobBundle/Entity/BatchJobUpdateField.php
// Table: `BatchJobUpdateField`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct BatchJobUpdateField {
    pub id: i32,
    #[sqlx(rename = "batchJob_id")]
    pub batch_job_id: Option<i32>,
    pub property: String,
    pub value: String,
    pub description: String,
    pub dynamic: bool,
}
