// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ImageBundle/Entity/CachedImage.php
// Table: `CachedImage`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct CachedImage {
    pub id: i32,
    #[sqlx(rename = "originalId")]
    pub original_id: i32,
    #[sqlx(rename = "originalType")]
    pub original_type: String,
    #[sqlx(rename = "cacheFile")]
    pub cache_file: String,
}
