// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/CronLoggerBundle/Entity/CronLogger.php
// Table: `CronLogger`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct CronLogger {
    pub id: i32,
    #[sqlx(rename = "lastRunDate")]
    pub last_run_date: Option<chrono::NaiveDateTime>,
    pub cronjob: String,
}
