// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/DistributorBundle/Entity/Distributor.php
// Table: `Distributor`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct Distributor {
    pub id: i32,
    pub name: String,
    pub address: Option<String>,
    pub url: Option<String>,
    pub phone: Option<String>,
    pub fax: Option<String>,
    pub email: Option<String>,
    pub comment: Option<String>,
    pub skuurl: Option<String>,
    #[sqlx(rename = "enabledForReports")]
    pub enabled_for_reports: bool,
}
