// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/DistributorBundle/Entity/Distributor.php
// Table: `Distributor`, REST: `/api/distributors`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct Distributor {
    pub id: i32,
    pub name: String,
    pub address: Option<String>,
    pub url: Option<String>,
    pub phone: Option<String>,
    pub fax: Option<String>,
    pub email: Option<String>,
    pub comment: Option<String>,
    pub skuurl: Option<String>,
    #[sqlx(rename = "enabledForReports")]
    pub enabled_for_reports: bool,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<Distributor>>, (StatusCode, String)>
{
    sqlx::query_as::<_, Distributor>("SELECT * FROM `Distributor` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in Distributor::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
