// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/FootprintBundle/Entity/FootprintCategory.php
// Table: `FootprintCategory`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct FootprintCategory {
    pub id: i32,
    pub lft: i32,
    pub rgt: i32,
    pub lvl: i32,
    pub root: Option<i32>,
    pub name: String,
    pub description: Option<String>,
    pub parent_id: Option<i32>,
    #[sqlx(rename = "categoryPath")]
    pub category_path: Option<String>,
}
