// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/FootprintBundle/Entity/Footprint.php
// Table: `Footprint`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct Footprint {
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub category_id: Option<i32>,
}
