// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/FootprintBundle/Entity/Footprint.php
// Table: `Footprint`, REST: `/api/footprints`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct Footprint {
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub category_id: Option<i32>,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<Footprint>>, (StatusCode, String)>
{
    sqlx::query_as::<_, Footprint>("SELECT * FROM `Footprint` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in Footprint::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
