// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/FrontendBundle/Entity/GridPreset.php
// Table: `GridPreset`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct GridPreset {
    pub id: i32,
    pub grid: String,
    pub name: String,
    pub configuration: String,
    #[sqlx(rename = "gridDefault")]
    pub grid_default: bool,
}
