// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ImportBundle/Entity/ImportPreset.php
// Table: `ImportPreset`, REST: `/api/import_presets`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct ImportPreset {
    pub id: i32,
    #[sqlx(rename = "baseEntity")]
    pub base_entity: String,
    pub name: String,
    pub configuration: String,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<ImportPreset>>, (StatusCode, String)>
{
    sqlx::query_as::<_, ImportPreset>("SELECT * FROM `ImportPreset` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in ImportPreset::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
