// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ManufacturerBundle/Entity/Manufacturer.php
// Table: `Manufacturer`, REST: `/api/manufacturers`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct Manufacturer {
    pub id: i32,
    pub name: String,
    pub address: Option<String>,
    pub url: Option<String>,
    pub email: Option<String>,
    pub comment: Option<String>,
    pub phone: Option<String>,
    pub fax: Option<String>,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<Manufacturer>>, (StatusCode, String)>
{
    sqlx::query_as::<_, Manufacturer>("SELECT * FROM `Manufacturer` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in Manufacturer::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
