// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ManufacturerBundle/Entity/ManufacturerICLogo.php
// Table: `ManufacturerICLogo`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct ManufacturerICLogo {
    pub id: i32,
    pub r#type: String,
    pub filename: String,
    pub originalname: Option<String>,
    pub mimetype: String,
    pub size: i32,
    pub extension: Option<String>,
    pub description: Option<String>,
    pub created: Option<chrono::NaiveDateTime>,
    pub manufacturer_id: Option<i32>,
}
