// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ManufacturerBundle/Entity/Manufacturer.php
// Table: `Manufacturer`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct Manufacturer {
    pub id: i32,
    pub name: String,
    pub address: Option<String>,
    pub url: Option<String>,
    pub email: Option<String>,
    pub comment: Option<String>,
    pub phone: Option<String>,
    pub fax: Option<String>,
}
