// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/PartBundle/Entity/MetaPartParameterCriteria.php
// Table: `MetaPartParameterCriteria`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct MetaPartParameterCriteria {
    pub id: i32,
    pub part_id: Option<i32>,
    #[sqlx(rename = "partParameterName")]
    pub part_parameter_name: String,
    pub operator: String,
    pub value: Option<f64>,
    #[sqlx(rename = "normalizedValue")]
    pub normalized_value: Option<f64>,
    #[sqlx(rename = "siPrefix_id")]
    pub si_prefix_id: Option<i32>,
    #[sqlx(rename = "stringValue")]
    pub string_value: String,
    #[sqlx(rename = "valueType")]
    pub value_type: String,
    pub unit_id: Option<i32>,
}
