// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit.

use axum::{routing::get, Router};

use crate::AppState;

pub mod batch_job;
pub mod batch_job_query_field;
pub mod batch_job_update_field;
pub mod cached_image;
pub mod cron_logger;
pub mod distributor;
pub mod footprint;
pub mod footprint_attachment;
pub mod footprint_category;
pub mod footprint_image;
pub mod grid_preset;
pub mod import_preset;
pub mod manufacturer;
pub mod manufacturer_ic_logo;
pub mod meta_part_parameter_criteria;
pub mod part;
pub mod part_attachment;
pub mod part_category;
pub mod part_distributor;
pub mod part_manufacturer;
pub mod part_measurement_unit;
pub mod part_parameter;
pub mod project;
pub mod project_attachment;
pub mod project_part;
pub mod project_run;
pub mod project_run_part;
pub mod report;
pub mod report_part;
pub mod report_project;
pub mod si_prefix;
pub mod statistic_snapshot;
pub mod statistic_snapshot_unit;
pub mod stock_entry;
pub mod storage_location;
pub mod storage_location_category;
pub mod storage_location_image;
pub mod system_notice;
pub mod system_preference;
pub mod temp_image;
pub mod temp_uploaded_file;
pub mod tip_of_the_day;
pub mod tip_of_the_day_history;
pub mod unit;
pub mod user;
pub mod user_preference;
pub mod user_provider;

/// Build a router with all generated GET-list endpoints registered.
pub fn routes() -> Router<AppState> {
    Router::new()
        .route("/api/batch_jobs", get(batch_job::list))
        .route("/api/grid_presets", get(grid_preset::list))
        .route("/api/import_presets", get(import_preset::list))
        .route("/api/stock_entries", get(stock_entry::list))
        .route("/api/system_preferences", get(system_preference::list))
        .route("/api/tip_of_the_days", get(tip_of_the_day::list))
        .route("/api/tip_of_the_day_histories", get(tip_of_the_day_history::list))
        .route("/api/users", get(user::list))
        .route("/api/user_preferences", get(user_preference::list))
        .route("/api/user_providers", get(user_provider::list))
}
