// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/PartBundle/Entity/PartMeasurementUnit.php
// Table: `PartUnit`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct PartMeasurementUnit {
    pub id: i32,
    pub name: String,
    #[sqlx(rename = "shortName")]
    pub short_name: String,
    pub is_default: bool,
}
