// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/PartBundle/Entity/PartAttachment.php
// Table: `PartAttachment`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct PartAttachment {
    pub id: i32,
    pub r#type: String,
    pub filename: String,
    pub originalname: Option<String>,
    pub mimetype: String,
    pub size: i32,
    pub extension: Option<String>,
    pub description: Option<String>,
    pub created: Option<chrono::NaiveDateTime>,
    #[sqlx(rename = "isImage")]
    pub is_image: Option<bool>,
    pub part_id: Option<i32>,
}
