// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/PartBundle/Entity/Part.php
// Table: `Part`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct Part {
    pub id: i32,
    pub category_id: Option<i32>,
    pub name: String,
    pub description: Option<String>,
    pub footprint_id: Option<i32>,
    #[sqlx(rename = "partUnit_id")]
    pub part_unit_id: Option<i32>,
    #[sqlx(rename = "storageLocation_id")]
    pub storage_location_id: Option<i32>,
    pub comment: String,
    #[sqlx(rename = "stockLevel")]
    pub stock_level: i32,
    #[sqlx(rename = "minStockLevel")]
    pub min_stock_level: i32,
    #[sqlx(rename = "averagePrice")]
    pub average_price: rust_decimal::Decimal,
    pub status: Option<String>,
    #[sqlx(rename = "needsReview")]
    pub needs_review: bool,
    #[sqlx(rename = "partCondition")]
    pub part_condition: Option<String>,
    #[sqlx(rename = "productionRemarks")]
    pub production_remarks: Option<String>,
    #[sqlx(rename = "createDate")]
    pub create_date: Option<chrono::NaiveDateTime>,
    #[sqlx(rename = "internalPartNumber")]
    pub internal_part_number: Option<String>,
    pub removals: bool,
    #[sqlx(rename = "lowStock")]
    pub low_stock: bool,
    #[sqlx(rename = "metaPart")]
    pub meta_part: bool,
}
