// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/PartBundle/Entity/PartDistributor.php
// Table: `PartDistributor`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct PartDistributor {
    pub id: i32,
    pub part_id: Option<i32>,
    pub distributor_id: Option<i32>,
    #[sqlx(rename = "orderNumber")]
    pub order_number: Option<String>,
    #[sqlx(rename = "packagingUnit")]
    pub packaging_unit: i32,
    pub price: Option<rust_decimal::Decimal>,
    pub currency: Option<String>,
    pub sku: Option<String>,
    #[sqlx(rename = "ignoreForReports")]
    pub ignore_for_reports: Option<bool>,
}
