// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/PartBundle/Entity/PartParameter.php
// Table: `PartParameter`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct PartParameter {
    pub id: i32,
    pub part_id: Option<i32>,
    pub name: String,
    pub description: String,
    pub unit_id: Option<i32>,
    pub value: Option<f64>,
    #[sqlx(rename = "normalizedValue")]
    pub normalized_value: Option<f64>,
    #[sqlx(rename = "maximumValue")]
    pub maximum_value: Option<f64>,
    #[sqlx(rename = "normalizedMaxValue")]
    pub normalized_max_value: Option<f64>,
    #[sqlx(rename = "minimumValue")]
    pub minimum_value: Option<f64>,
    #[sqlx(rename = "normalizedMinValue")]
    pub normalized_min_value: Option<f64>,
    #[sqlx(rename = "stringValue")]
    pub string_value: String,
    #[sqlx(rename = "valueType")]
    pub value_type: String,
    #[sqlx(rename = "siPrefix_id")]
    pub si_prefix_id: Option<i32>,
    #[sqlx(rename = "minSiPrefix_id")]
    pub min_si_prefix_id: Option<i32>,
    #[sqlx(rename = "maxSiPrefix_id")]
    pub max_si_prefix_id: Option<i32>,
}
