// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/PartBundle/Entity/PartMeasurementUnit.php
// Table: `PartUnit`, REST: `/api/part_measurement_units`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct PartMeasurementUnit {
    pub id: i32,
    pub name: String,
    #[sqlx(rename = "shortName")]
    pub short_name: String,
    pub is_default: bool,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<PartMeasurementUnit>>, (StatusCode, String)>
{
    sqlx::query_as::<_, PartMeasurementUnit>("SELECT * FROM `PartUnit` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in PartMeasurementUnit::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
