// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/PartBundle/Entity/PartManufacturer.php
// Table: `PartManufacturer`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct PartManufacturer {
    pub id: i32,
    pub part_id: Option<i32>,
    pub manufacturer_id: Option<i32>,
    #[sqlx(rename = "partNumber")]
    pub part_number: Option<String>,
}
