// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ProjectBundle/Entity/ProjectRunPart.php
// Table: `ProjectRunPart`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct ProjectRunPart {
    pub id: i32,
    #[sqlx(rename = "projectRun_id")]
    pub project_run_id: Option<i32>,
    pub part_id: Option<i32>,
    pub quantity: i32,
    #[sqlx(rename = "lotNumber")]
    pub lot_number: String,
}
