// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ProjectBundle/Entity/ProjectRun.php
// Table: `ProjectRun`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct ProjectRun {
    pub id: i32,
    #[sqlx(rename = "runDateTime")]
    pub run_date_time: Option<chrono::NaiveDateTime>,
    pub project_id: Option<i32>,
    pub quantity: i32,
}
