// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ProjectBundle/Entity/ProjectPart.php
// Table: `ProjectPart`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct ProjectPart {
    pub id: i32,
    pub part_id: Option<i32>,
    pub quantity: i32,
    pub project_id: Option<i32>,
    pub remarks: Option<String>,
    #[sqlx(rename = "overageType")]
    pub overage_type: String,
    pub overage: i32,
    #[sqlx(rename = "lotNumber")]
    pub lot_number: String,
}
