// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ProjectBundle/Entity/Project.php
// Table: `Project`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct Project {
    pub id: i32,
    pub name: String,
    pub user_id: Option<i32>,
    pub description: Option<String>,
}
