// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ProjectBundle/Entity/ReportProject.php
// Table: `ReportProject`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct ReportProject {
    pub id: i32,
    pub report_id: Option<i32>,
    pub project_id: Option<i32>,
    pub quantity: i32,
}
