// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ProjectBundle/Entity/Report.php
// Table: `Report`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct Report {
    pub id: i32,
    pub name: Option<String>,
    #[sqlx(rename = "createDateTime")]
    pub create_date_time: Option<chrono::NaiveDateTime>,
}
