// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/SiPrefixBundle/Entity/SiPrefix.php
// Table: `SiPrefix`, REST: `/api/si_prefixes`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct SiPrefix {
    pub id: i32,
    pub prefix: String,
    pub symbol: String,
    pub exponent: i32,
    pub base: i32,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<SiPrefix>>, (StatusCode, String)>
{
    sqlx::query_as::<_, SiPrefix>("SELECT * FROM `SiPrefix` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in SiPrefix::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
