// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/SiPrefixBundle/Entity/SiPrefix.php
// Table: `SiPrefix`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct SiPrefix {
    pub id: i32,
    pub prefix: String,
    pub symbol: String,
    pub exponent: i32,
    pub base: i32,
}
