// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/StatisticBundle/Entity/StatisticSnapshot.php
// Table: `StatisticSnapshot`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct StatisticSnapshot {
    pub id: i32,
    #[sqlx(rename = "dateTime")]
    pub date_time: Option<chrono::NaiveDateTime>,
    pub parts: i32,
    pub categories: i32,
}
