// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/StatisticBundle/Entity/StatisticSnapshotUnit.php
// Table: `StatisticSnapshotUnit`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct StatisticSnapshotUnit {
    pub id: i32,
    #[sqlx(rename = "statisticSnapshot_id")]
    pub statistic_snapshot_id: Option<i32>,
    #[sqlx(rename = "partUnit_id")]
    pub part_unit_id: Option<i32>,
    #[sqlx(rename = "stockLevel")]
    pub stock_level: i32,
}
