// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/StockBundle/Entity/StockEntry.php
// Table: `StockEntry`, REST: `/api/stock_entries`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct StockEntry {
    pub id: i32,
    #[sqlx(rename = "stockLevel")]
    pub stock_level: i32,
    pub part_id: Option<i32>,
    pub user_id: Option<i32>,
    pub price: Option<rust_decimal::Decimal>,
    #[sqlx(rename = "dateTime")]
    pub date_time: Option<chrono::NaiveDateTime>,
    pub correction: bool,
    pub comment: Option<String>,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<StockEntry>>, (StatusCode, String)>
{
    sqlx::query_as::<_, StockEntry>("SELECT * FROM `StockEntry` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in StockEntry::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
