// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/StorageLocationBundle/Entity/StorageLocation.php
// Table: `StorageLocation`, REST: `/api/storage_locations`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct StorageLocation {
    pub id: i32,
    pub name: String,
    pub category_id: Option<i32>,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<StorageLocation>>, (StatusCode, String)>
{
    sqlx::query_as::<_, StorageLocation>("SELECT * FROM `StorageLocation` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in StorageLocation::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
