// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/StorageLocationBundle/Entity/StorageLocation.php
// Table: `StorageLocation`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct StorageLocation {
    pub id: i32,
    pub name: String,
    pub category_id: Option<i32>,
}
