// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/StorageLocationBundle/Entity/StorageLocationCategory.php
// Table: `StorageLocationCategory`, REST: `/api/storage_location_categories`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct StorageLocationCategory {
    pub id: i32,
    pub lft: i32,
    pub rgt: i32,
    pub lvl: i32,
    pub root: Option<i32>,
    pub name: String,
    pub description: Option<String>,
    pub parent_id: Option<i32>,
    #[sqlx(rename = "categoryPath")]
    pub category_path: Option<String>,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<StorageLocationCategory>>, (StatusCode, String)>
{
    sqlx::query_as::<_, StorageLocationCategory>("SELECT * FROM `StorageLocationCategory` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in StorageLocationCategory::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
