// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/StorageLocationBundle/Entity/StorageLocationImage.php
// Table: `StorageLocationImage`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct StorageLocationImage {
    pub id: i32,
    pub r#type: String,
    pub filename: String,
    pub originalname: Option<String>,
    pub mimetype: String,
    pub size: i32,
    pub extension: Option<String>,
    pub description: Option<String>,
    pub created: Option<chrono::NaiveDateTime>,
    #[sqlx(rename = "storageLocation_id")]
    pub storage_location_id: Option<i32>,
}
