// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/CoreBundle/Entity/SystemNotice.php
// Table: `SystemNotice`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct SystemNotice {
    pub id: i32,
    pub date: Option<chrono::NaiveDateTime>,
    pub title: String,
    pub description: String,
    pub acknowledged: bool,
    pub r#type: String,
}
