// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/SystemPreferenceBundle/Entity/SystemPreference.php
// Table: `SystemPreference`, REST: `/api/system_preferences`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct SystemPreference {
    #[sqlx(rename = "preferenceKey")]
    pub preference_key: String,
    #[sqlx(rename = "preferenceValue")]
    pub preference_value: String,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<SystemPreference>>, (StatusCode, String)>
{
    sqlx::query_as::<_, SystemPreference>("SELECT * FROM `SystemPreference` LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in SystemPreference::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
