// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/UploadedFileBundle/Entity/TempUploadedFile.php
// Table: `TempUploadedFile`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct TempUploadedFile {
    pub id: i32,
    pub r#type: String,
    pub filename: String,
    pub originalname: Option<String>,
    pub mimetype: String,
    pub size: i32,
    pub extension: Option<String>,
    pub description: Option<String>,
    pub created: Option<chrono::NaiveDateTime>,
}
