// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/ImageBundle/Entity/TempImage.php
// Table: `TempImage`

use serde::Serialize;
use sqlx::FromRow;

#[allow(dead_code)]
#[derive(Debug, Serialize, FromRow)]
pub struct TempImage {
    pub id: i32,
    pub r#type: String,
    pub filename: String,
    pub originalname: Option<String>,
    pub mimetype: String,
    pub size: i32,
    pub extension: Option<String>,
    pub description: Option<String>,
    pub created: Option<chrono::NaiveDateTime>,
}
