// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/TipOfTheDayBundle/Entity/TipOfTheDay.php
// Table: `TipOfTheDay`, REST: `/api/tip_of_the_days`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct TipOfTheDay {
    pub id: i32,
    pub name: String,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<TipOfTheDay>>, (StatusCode, String)>
{
    sqlx::query_as::<_, TipOfTheDay>("SELECT * FROM `TipOfTheDay` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in TipOfTheDay::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
