// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/TipOfTheDayBundle/Entity/TipOfTheDayHistory.php
// Table: `TipOfTheDayHistory`, REST: `/api/tip_of_the_day_histories`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct TipOfTheDayHistory {
    pub id: i32,
    pub name: String,
    pub user_id: Option<i32>,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<TipOfTheDayHistory>>, (StatusCode, String)>
{
    sqlx::query_as::<_, TipOfTheDayHistory>("SELECT * FROM `TipOfTheDayHistory` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in TipOfTheDayHistory::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
