// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/UnitBundle/Entity/Unit.php
// Table: `Unit`, REST: `/api/units`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct Unit {
    pub id: i32,
    pub name: String,
    pub symbol: String,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<Unit>>, (StatusCode, String)>
{
    sqlx::query_as::<_, Unit>("SELECT * FROM `Unit` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in Unit::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
