// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/AuthBundle/Entity/UserPreference.php
// Table: `UserPreference`, REST: `/api/user_preferences`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct UserPreference {
    #[sqlx(rename = "preferenceKey")]
    pub preference_key: String,
    #[sqlx(rename = "preferenceValue")]
    pub preference_value: String,
    pub user_id: Option<i32>,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<UserPreference>>, (StatusCode, String)>
{
    sqlx::query_as::<_, UserPreference>("SELECT * FROM `UserPreference` LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in UserPreference::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
