// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/AuthBundle/Entity/User.php
// Table: `PartKeeprUser`, REST: `/api/users`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct User {
    pub id: i32,
    pub username: String,
    pub password: Option<String>,
    pub email: Option<String>,
    pub admin: bool,
    pub legacy: bool,
    #[sqlx(rename = "lastSeen")]
    pub last_seen: Option<chrono::NaiveDateTime>,
    pub provider_id: Option<i32>,
    pub active: bool,
    pub protected: bool,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<User>>, (StatusCode, String)>
{
    sqlx::query_as::<_, User>("SELECT * FROM `PartKeeprUser` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in User::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
