// AUTO-GENERATED by scripts/generate-rust-models.py — do not edit by hand.
// Source: reference/PartKeepr/src/PartKeepr/AuthBundle/Entity/UserProvider.php
// Table: `UserProvider`, REST: `/api/user_providers`

use axum::{extract::State, http::StatusCode, Json};
use serde::Serialize;
use sqlx::FromRow;
use sqlx::MySqlPool;

#[derive(Debug, Serialize, FromRow)]
pub struct UserProvider {
    pub id: i32,
    pub r#type: String,
    pub editable: bool,
}

pub async fn list(State(pool): State<MySqlPool>)
    -> Result<Json<Vec<UserProvider>>, (StatusCode, String)>
{
    sqlx::query_as::<_, UserProvider>("SELECT * FROM `UserProvider` ORDER BY id LIMIT 100")
        .fetch_all(&pool).await
        .map(Json)
        .map_err(|e| {
            tracing::error!(error = %e, "db error in UserProvider::list");
            (StatusCode::INTERNAL_SERVER_ERROR, "internal error".into())
        })
}
