#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# One-shot helper to migrate the jlcparts SQLite from a dev location
# (e.g. ~/.local/share/partkeepr-ng/) to the canonical prod layout at
# /var/lib/partkeepr-ng/, and install the weekly cron wrapper.
#
# Idempotent: re-runs are no-ops if everything is already in place.
# Needs sudo for the /var/lib + /etc/cron.weekly writes.
#
# Usage:
#   ./scripts/setup-jlcparts-paths.sh [-u USER]
#
#     -u USER   own /var/lib/partkeepr-ng as this user (default: $USER)
#     -h        help

set -euo pipefail

OWNER="${USER}"
ARCHIVE_DIR=""        # default = $DATA_DIR/jlc-archive (alongside the DB)
while getopts "u:A:h" opt; do
    case $opt in
        u) OWNER="$OPTARG" ;;
        A) ARCHIVE_DIR="$OPTARG" ;;
        h)
            sed -n '4,/^$/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *) exit 2 ;;
    esac
done

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATA_DIR="/var/lib/partkeepr-ng"
LOG_DIR="/var/log/partkeepr-ng"
CRON_DEST="/etc/cron.weekly/partkeepr-ng-jlcparts-sync"
ENV_FILE="$REPO_ROOT/backend/.env"
DEV_SQLITE="$HOME/.local/share/partkeepr-ng/jlcparts.sqlite3"
PROD_SQLITE="$DATA_DIR/jlcparts.sqlite3"

step() { printf '\n[%s] %s\n' "$(date +%H:%M:%S)" "$*"; }

# ---- 1. Create the system data + log dirs -----------------------------------

step "creating $DATA_DIR + $LOG_DIR (sudo)"
# Only create $DATA_DIR/jlc-archive if archives aren't being relocated
# elsewhere (e.g. to an NFS-mounted ZFS dataset).
if [[ -z "$ARCHIVE_DIR" ]]; then
    sudo mkdir -p "$DATA_DIR/jlc-archive" "$LOG_DIR"
else
    sudo mkdir -p "$DATA_DIR" "$LOG_DIR"
    step "archives configured for $ARCHIVE_DIR (assumed pre-created with right ownership)"
fi
sudo chown -R "$OWNER":"$(id -gn "$OWNER")" "$DATA_DIR" "$LOG_DIR"

# ---- 2. Migrate the dev SQLite if present ----------------------------------

if [[ -f "$PROD_SQLITE" ]]; then
    step "$PROD_SQLITE already exists — leaving alone"
elif [[ -f "$DEV_SQLITE" ]]; then
    step "moving $DEV_SQLITE → $PROD_SQLITE"
    mv "$DEV_SQLITE" "$PROD_SQLITE"
    # Try to clean up the now-empty dev dir.
    rmdir "$(dirname "$DEV_SQLITE")" 2>/dev/null || true
else
    step "no dev SQLite found at $DEV_SQLITE — will be created on first sync run"
fi

# ---- 3. Update backend/.env to point at the prod path ----------------------

if [[ -f "$ENV_FILE" ]]; then
    if grep -q '^PARTKEEPR_JLCPARTS_DB_PATH=' "$ENV_FILE"; then
        # In-place rewrite — preserve any value the user had.
        step "rewriting PARTKEEPR_JLCPARTS_DB_PATH in $ENV_FILE"
        sed -i "s|^PARTKEEPR_JLCPARTS_DB_PATH=.*|PARTKEEPR_JLCPARTS_DB_PATH=$PROD_SQLITE|" "$ENV_FILE"
    else
        step "appending PARTKEEPR_JLCPARTS_DB_PATH to $ENV_FILE"
        printf '\nPARTKEEPR_JLCPARTS_DB_PATH=%s\n' "$PROD_SQLITE" >> "$ENV_FILE"
    fi
else
    step "no $ENV_FILE — skipping env update (you'll need to set PARTKEEPR_JLCPARTS_DB_PATH yourself)"
fi

# ---- 4. Install the cron.weekly wrapper -----------------------------------

WRAPPER_SRC="$REPO_ROOT/ebuild/files/jlcparts-sync.cron"
SYNC_SCRIPT_SRC="$REPO_ROOT/scripts/jlcparts-sync.sh"

if [[ ! -f "$WRAPPER_SRC" ]]; then
    echo "error: cron wrapper missing at $WRAPPER_SRC" >&2
    exit 1
fi

step "installing $CRON_DEST (sudo)"
sudo install -m 0755 "$WRAPPER_SRC" "$CRON_DEST"

# The cron wrapper expects $SYNC_SCRIPT at /usr/share/partkeepr-ng/scripts/.
# For a dev box that path doesn't exist; bridge with a site-config override.
SITE_CONF="/etc/partkeepr-ng/jlcparts.conf"
step "writing $SITE_CONF (sudo) — points the cron wrapper at the dev source tree"
sudo mkdir -p "$(dirname "$SITE_CONF")"
sudo tee "$SITE_CONF" >/dev/null <<EOF
# Auto-generated by setup-jlcparts-paths.sh on $(date -u +%FT%TZ).
# Overrides defaults baked into /etc/cron.weekly/partkeepr-ng-jlcparts-sync.
SYNC_SCRIPT="$SYNC_SCRIPT_SRC"
DATA_DIR="$DATA_DIR"
ARCHIVE_DIR="$ARCHIVE_DIR"
LOG_FILE="$LOG_DIR/jlcparts-sync.log"
PARTKEEPR_USER="$OWNER"
KEEP_ARCHIVES=4
EOF

# ---- 5. Summary ------------------------------------------------------------

cat <<EOF

[done]
  data dir:        $DATA_DIR  (owned by $OWNER)
  archive dir:     $DATA_DIR/jlc-archive
  log file:        $LOG_DIR/jlcparts-sync.log
  cron job:        $CRON_DEST   (runs weekly via anacron / cronie)
  site config:     $SITE_CONF
  env updated:     PARTKEEPR_JLCPARTS_DB_PATH=$PROD_SQLITE

Sanity-test the cron job now without waiting a week:
  sudo $CRON_DEST
  tail $LOG_DIR/jlcparts-sync.log

Restart the backend to pick up the new env value.
EOF
